language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g mocha
  - npm install -g gulp
  - npm install
  - npm update
script: npm test
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
